task_name: eval

# eval_checkpoint: checkpoints/best.ckpt
# eval_checkpoint: outputs/2025-09-08/19-38-28/checkpoints/epoch_021.ckpt
# eval_checkpoint: outputs/2025-09-08/20-11-07/checkpoints/epoch_018.ckpt
# eval_checkpoint: outputs/2025-10-29/09-35-55/checkpoints/epoch_006.ckpt
# eval_checkpoint: outputs/2025-10-29/14-54-47/checkpoints/epoch_032.ckpt
# eval_checkpoint: outputs/2025-10-30/01-39-53/checkpoints/epoch_008.ckpt
# eval_checkpoint: outputs/2025-10-30/17-22-55/checkpoints/epoch_025.ckpt
eval_checkpoint: outputs/2025-10-30/20-17-39/checkpoints/epoch_011.ckpt
inference_img_path: test_infer.png
detection_threshold: 0.5

eval_mode: 0
# 0: Choose options
# 1: Visualize in bird's eye view
# 2: Visualize in 3D point cloud
# 3: Only quantitative evaluation mode

defaults:
  - _self_
  - data: roadsign_data
  - model: pointpillars
  - callbacks: default
  - logger: mlflow
  - trainer: ddp
  - paths: default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:  
  output_subdir: null  
  run:  
    dir: .
