ckpt_path: null
training_model: True
exporting_onnx: False
down_stride: 8

defaults:
  - _self_
  - data: roadsign_data
  - model: pointpillars
  - callbacks: default
  - logger: mlflow
  - trainer: ddp
  - paths: default

task_name: train

confidence_threshold: null