# "~~~/~~~.pcd"의 형태가 되어야 합니다.
[Paths]
target_cloud_path = "path/to/your/map.pcd" 
source_cloud_path = "path/to/your/source.pcd"
result_pcd_path = "results/matched_cloud.pcd"

[Settings]
visualize_process = true
visualize_result = true
save_result_pcd = true